Repository pytorch/helion, pull requests merged in 2025-05, with the labels that each got.

#22 Add hl.constexpr specialization
  examples/matmul.py
  examples/softmax.py
  examples/template_via_closure.py
  helion/_compiler/compile_environment.py
  helion/_compiler/generate_ast.py
  helion/_compiler/host_function.py
  helion/language/__init__.py
  helion/language/constexpr.py
  helion/runtime/kernel.py
  test/test_constexpr.py
  test/test_examples.py
  test/test_matmul.py
  test/test_reductions.py
  test/test_type_propagation.py
Labels: CLA Signed

#23 Fix license file for PEP 621
  pyproject.toml
Labels: CLA Signed

#25 Use search-strategy: all for all site packages in pyre config
  .pyre_configuration
Labels: CLA Signed

#27 Trigger CI on pull requests made by ghstack
  .github/workflows/test.yml
Labels: CLA Signed

#30 Add hl.register_block_size and explicit tile sizes
  examples/softmax.py
  helion/_compiler/compile_environment.py
  helion/_compiler/device_function.py
  helion/_compiler/device_ir.py
  helion/_compiler/generate_ast.py
  helion/_compiler/host_function.py
  helion/_compiler/indexing_strategy.py
  helion/_compiler/inductor_lowering.py
  helion/_compiler/reduction_strategy.py
  helion/_compiler/roll_reduction.py
  helion/_compiler/tile_dispatch.py
  helion/_compiler/tile_index_proxy.py
  helion/_compiler/tile_strategy.py
  helion/_compiler/type_propagation.py
  helion/_compiler/variable_origin.py
  helion/autotuner/config_spec.py
  helion/exc.py
  helion/language/__init__.py
  helion/language/_tracing_ops.py
  helion/language/creation_ops.py
  helion/language/loops.py
  pyproject.toml
  test/test_examples.py
  test/test_loops.py
  test/test_matmul.py
  test/test_reductions.py
Labels: CLA Signed

#31 Update lint github workflow
  .github/workflows/lint.yml
  .github/workflows/test.yml
  lint.sh
Labels: CLA Signed

#36 Add ../pytorch-nightly to Pyre optional_search_path
  .pyre_configuration
Labels: CLA Signed

#35 Fix TensorDescriptor handling in _find_device
  helion/_compat.py
  helion/_compiler/output_header.py
  helion/runtime/kernel.py
  test/test_matmul.py
Labels: CLA Signed

#37 Add HELION_USE_DEFAULT_CONFIG env var to force use default config
  helion/runtime/settings.py
Labels: CLA Signed

#38 Make BlockSizeOrigin host_str return 1 for block_size=1 case
  helion/_compiler/variable_origin.py
Labels: CLA Signed

#40 [2nd try] Make BlockSizeOrigin host_str return 1 for block_size=1 case
  helion/_compiler/variable_origin.py
Labels: CLA Signed

#43 Add more pytorchbot utils
  .github/scripts/check_labels.py
  .github/scripts/label_utils.py
  .github/scripts/syncbranches.py
Labels: CLA Signed

#47 Minor fix on the matmul example dim notation
  examples/matmul.py
Labels: CLA Signed

#49 Add the core properties to Config object
  .pre-commit-config.yaml
  README.md
  helion/_testing.py
  helion/autotuner/config_spec.py
  helion/runtime/config.py
  helion/runtime/kernel.py
  pyproject.toml
  requirements.txt
Labels: CLA Signed, merging, topic: not user facing, merged

#55 Switch build system to Hatchling which has much better Language Server support
  pyproject.toml
  setup.py
Labels: CLA Signed

#50 Support torch factory functions inside device loop
  helion/_compiler/generate_ast.py
  helion/_compiler/inductor_lowering.py
  test/test_misc.py
Labels: CLA Signed, topic: not user facing, merged

#56 Add attention example and fix some bugs
  examples/attention.py
  examples/softmax.py
  helion/_compiler/compile_environment.py
  helion/_compiler/indexing_strategy.py
  helion/_compiler/inductor_lowering.py
  helion/_compiler/output_header.py
  helion/_compiler/roll_reduction.py
  helion/autotuner/config_spec.py
  helion/language/_tracing_ops.py
  helion/language/loops.py
  pyproject.toml
  test/test_examples.py
Labels: CLA Signed

#58 Fix bug where non-tensor variables are not exposed to inner loops
  helion/_compiler/device_ir.py
  test/test_loops.py
Labels: CLA Signed

#59 Add `hl.grid(...)` support
  helion/_compiler/compile_environment.py
  helion/_compiler/device_ir.py
  helion/_compiler/indexing_strategy.py
  helion/_compiler/tile_dispatch.py
  helion/_compiler/tile_strategy.py
  helion/_compiler/type_propagation.py
  helion/language/__init__.py
  helion/language/loops.py
  test/test_loops.py
Labels: CLA Signed

#64 Fix more unit tests
  helion/_compat.py
Labels: CLA Signed, fb-exported

#65 Fix test_matmul_tensor_descriptor unit test
  test/test_matmul.py
Labels: CLA Signed

#69 Kill pytorch merge bot
  .github/merge_rules.yaml
  .github/pytorch-probot.yml
  .github/scripts/check_labels.py
  .github/scripts/github_utils.py
  .github/scripts/gitutils.py
  .github/scripts/label_utils.py
  .github/scripts/syncbranches.py
  .github/scripts/trymerge.py
  .github/scripts/trymerge_explainer.py
  .github/workflows/merge.yml
  .github/workflows/revert.yml
Labels: CLA Signed

#63 Prototyping an hl.atomic opp
  helion/_compiler/device_ir.py
  helion/_compiler/indexing_strategy.py
  helion/language/__init__.py
  helion/language/_decorators.py
  helion/language/memory_ops.py
  pyproject.toml
  test/test_atomic_add.py
Labels: CLA Signed

#72 Add hl.specialize and improve reduction handling
  examples/attention.py
  helion/__init__.py
  helion/_compiler/compile_environment.py
  helion/_compiler/device_function.py
  helion/_compiler/generate_ast.py
  helion/_compiler/host_function.py
  helion/_compiler/indexing_strategy.py
  helion/_compiler/inductor_lowering.py
  helion/_compiler/output_header.py
  helion/_compiler/reduction_strategy.py
  helion/_compiler/tile_strategy.py
  helion/_compiler/type_propagation.py
  helion/exc.py
  helion/language/__init__.py
  helion/language/_decorators.py
  helion/language/constexpr.py
  helion/runtime/kernel.py
  test/test_examples.py
  test/test_reductions.py
  test/test_specialize.py
  test/test_views.py
Labels: CLA Signed

#73 [test] Touch test/__init__.py to support more testing workflows
  .github/workflows/test.yml
  test/__init__.py
  test/test_closures.py
  test/test_examples.py
Labels: CLA Signed

#82 Add support for hl.tile(begin, end) and hl.tile(begin, end, block_size)
  helion/_compiler/compile_environment.py
  helion/_compiler/type_propagation.py
  helion/language/loops.py
  test/test_loops.py
Labels: CLA Signed

#84 Don't re-wrap exceptions in exc.TorchOpTracingError
  helion/_compiler/type_propagation.py
Labels: CLA Signed

#89 Add hl.tile_index()
  helion/_compiler/compile_environment.py
  helion/_compiler/device_ir.py
  helion/_compiler/tile_index_proxy.py
  helion/_compiler/type_propagation.py
  helion/language/__init__.py
  helion/language/loops.py
  helion/language/tiles.py
  helion/runtime/kernel.py
  test/test_indexing.py
Labels: CLA Signed

#95 Add filecheck dependency
  pyproject.toml
  requirements.txt
Labels: CLA Signed

#93 Add env HELION_PRINT_OUTPUT_CODE=1
  helion/runtime/kernel.py
  helion/runtime/settings.py
Labels: CLA Signed

#101 Bump project version
  pyproject.toml
Labels: CLA Signed

#103 Swap to using hatch vcs
  pyproject.toml
Labels: CLA Signed

#106 Beef up pre-commit checks
  .pre-commit-config.yaml
Labels: CLA Signed

#105 Add jagged_dense_add_2d example in generalize tensor indexing
  examples/jagged_dense_add.py
  helion/_compiler/indexing_strategy.py
  helion/_compiler/tile_strategy.py
  helion/exc.py
  helion/language/loops.py
  test/test_atomic_add.py
  test/test_broadcasting.py
  test/test_closures.py
  test/test_constexpr.py
  test/test_control_flow.py
  test/test_examples.py
  test/test_generate_ast.py
  test/test_indexing.py
  test/test_loops.py
  test/test_matmul.py
  test/test_misc.py
  test/test_reductions.py
  test/test_specialize.py
Labels: CLA Signed

#100 Update README.md with Helion logo
  README.md
Labels: CLA Signed

#109 Optimization pass to remove unneeded masking
  helion/_compiler/compile_environment.py
  helion/_compiler/indexing_strategy.py
  helion/_compiler/inductor_lowering.py
  helion/_compiler/node_masking.py
  helion/_compiler/reduction_strategy.py
  helion/_compiler/roll_reduction.py
  helion/_compiler/tile_strategy.py
  helion/language/_decorators.py
  helion/language/_tracing_ops.py
  helion/language/creation_ops.py
  helion/language/memory_ops.py
  helion/language/view_ops.py
  test/test_examples.py
  test/test_loops.py
  test/test_masking.py
  test/test_misc.py
  test/test_reductions.py
  test/test_specialize.py
  test/test_views.py
Labels: CLA Signed

#111 Improve mask optimization to cover control flow and inductor ops
  helion/_compiler/device_ir.py
  helion/_compiler/inductor_lowering.py
  helion/_compiler/node_masking.py
  helion/_compiler/roll_reduction.py
  helion/language/_tracing_ops.py
  test/test_examples.py
  test/test_loops.py
  test/test_masking.py
  test/test_misc.py
Labels: CLA Signed

#112 Expand README.md
  README.md
Labels: CLA Signed
