Repository pytorch/helion, pull requests merged in 2025-09, with the labels that each got.

#524 Add torch.stack support
  helion/_compiler/device_ir.py
  helion/_compiler/inductor_lowering.py
  test/test_views.expected
  test/test_views.py
Labels: CLA Signed

#545 Add torch compile to benchmark
  benchmarks/run.py
Labels: CLA Signed

#542 Fix issues with wrong dtypes in generated code
  helion/_compiler/dtype_utils.py
  helion/_compiler/inductor_lowering.py
  helion/_compiler/reduction_strategy.py
  helion/language/_tracing_ops.py
  helion/language/matmul_ops.py
  helion/runtime/settings.py
  test/test_associative_scan.expected
  test/test_closures.expected
  test/test_constexpr.expected
  test/test_control_flow.expected
  test/test_dot.expected
  test/test_dot.py
  test/test_examples.expected
  test/test_generate_ast.expected
  test/test_generate_ast.py
  test/test_grid.expected
  test/test_indexing.expected
  test/test_inline_asm_elementwise.expected
  test/test_loops.expected
  test/test_masking.expected
  test/test_matmul.expected
  test/test_misc.expected
  test/test_misc.py
  test/test_persistent_kernels.expected
  test/test_reduce.expected
  test/test_reductions.expected
  test/test_register_tunable.expected
  test/test_specialize.expected
  test/test_tensor_descriptor.expected
  test/test_views.expected
Labels: CLA Signed

#543 Limit concurrent precompile jobs while autotuning
  examples/segment_reduction.py
  helion/autotuner/base_search.py
  helion/language/loops.py
  helion/runtime/settings.py
Labels: CLA Signed

#544 Create basic helion benchmark runner
  .github/workflows/benchmark.yml
  .github/workflows/test.yml
  benchmarks/run.py
Labels: CLA Signed

#547 Add multi selection radio buttons
  .github/workflows/benchmark.yml
Labels: CLA Signed

#548 Fix benchmark condition
  .github/workflows/benchmark.yml
Labels: CLA Signed

#549 Move to dispatcher model for benchmarking
  .github/workflows/benchmark.yml
  .github/workflows/benchmark_dispatch.yml
Labels: CLA Signed

#554 Add jagged hstu attention example (i.e. ragged_attention)
  benchmarks/run.py
  examples/jagged_hstu_attn.py
  test/test_examples.expected
  test/test_examples.py
Labels: CLA Signed

#556 Update test-reports dir
  .github/workflows/benchmark.yml
Labels: CLA Signed

#560 Use profiler instead of inductor_benchmarker
  .github/workflows/benchmark.yml
Labels: CLA Signed

#570 Update benchmark.yml
  .github/workflows/benchmark.yml
Labels: CLA Signed

#567 [Benchmark] Use custom kernel metric mappings list to accomodate for inconsistent namings
  benchmarks/run.py
Labels: CLA Signed

#568 Add rms norm and cross entropy
  .github/workflows/benchmark.yml
  benchmarks/run.py
Labels: CLA Signed

#573 Update benchmark_dispatch.yml
  .github/workflows/benchmark_dispatch.yml
Labels: CLA Signed

#569 Update linters
  .pre-commit-config.yaml
  lint.sh
Labels: CLA Signed

#565 Print config for PassManager::run triton errors
  helion/autotuner/base_search.py
Labels: CLA Signed

#572 Error when invalid loop reduction number config is generated
  examples/rms_norm.py
  helion/autotuner/config_spec.py
Labels: CLA Signed

#574 Add `skipIfLowVRAM` or `use_default_config=False` to specific unit tests to enable local testing
  helion/_testing.py
  test/test_autotuner.py
  test/test_cache.py
  test/test_loops.py
  test/test_misc.py
Labels: CLA Signed

#576 Print warning if block_size is specified in interpret mode.
  helion/exc.py
  helion/language/loops.py
  test/test_ref_eager.py
Labels: CLA Signed

#580 [Benchmark] Fix layer_norm accuracy issue
  examples/layer_norm.py
  test/test_examples.expected
Labels: CLA Signed

#583 Do not benchmark twice
  helion/autotuner/differential_evolution.py
Labels: CLA Signed

#592 Fix tf32 warning
  helion/_testing.py
Labels: CLA Signed

#582 [Benchmark] geglu example and test
  benchmarks/run.py
  examples/geglu.py
  test/test_examples.expected
  test/test_examples.py
Labels: CLA Signed

#599 Print default config when running with it
  helion/runtime/kernel.py
Labels: CLA Signed

#597 Add rms_norm backward kernels
  examples/rms_norm.py
  test/test_examples.expected
  test/test_examples.py
Labels: CLA Signed, fb-exported, meta-exported

#604 Revert "Login to Docker from the workflows"
  .github/workflows/benchmark.yml
  .github/workflows/test.yml
Labels: CLA Signed, ci-no-td

#609 Fix static shape typo
  benchmarks/run.py
Labels: CLA Signed

#564 Add small dim size (<16) support to hl.dot and torch.addmm; Always prefer using `tl.dot(acc=...)` for addmm / baddbmm
  helion/_compiler/dtype_utils.py
  helion/_compiler/inductor_lowering.py
  helion/_compiler/matmul_utils.py
  helion/_compiler/roll_reduction.py
  helion/_testing.py
  helion/language/matmul_ops.py
  test/test_dot.expected
  test/test_dot.py
  test/test_examples.expected
  test/test_grid.expected
  test/test_loops.expected
  test/test_masking.expected
  test/test_matmul.expected
  test/test_persistent_kernels.expected
  test/test_register_tunable.expected
  test/test_specialize.expected
  test/test_tensor_descriptor.expected
Labels: CLA Signed

#611 [Benchmark] jsd kernel and test
  benchmarks/run.py
  examples/jsd.py
  test/test_examples.expected
  test/test_examples.py
Labels: CLA Signed

#595 Refactor autotune error handling
  helion/autotuner/base_search.py
  helion/autotuner/logger.py
  helion/runtime/precompile_shim.py
  test/test_autotuner.py
Labels: CLA Signed

#617 Possible fix for CI failures
  test/test_autotuner.py
Labels: CLA Signed

#615 [Benchmark] kl_div kernel and test
  benchmarks/run.py
  examples/kl_div.py
  test/test_examples.expected
  test/test_examples.py
Labels: CLA Signed

#618 Ignore TServiceRouterException errors while autotuning
  helion/autotuner/logger.py
Labels: CLA Signed

#632 Add more kernels to benchmarking
  .github/workflows/benchmark.yml
Labels: CLA Signed

#621 [Ref Mode] Fix hl.store for complex mask pattern
  helion/language/memory_ops.py
  test/test_indexing.py
Labels: CLA Signed

#625 Fix ValueError: numel (2097152) exceeds triton maximum tensor numel (1048576)
  helion/autotuner/config_generation.py
Labels: CLA Signed, fb-exported, meta-exported

#608 Always clear inductor cache before benchmark
  .github/workflows/benchmark.yml
Labels: CLA Signed

#636 Make hl.specialize work on sequences
  helion/language/constexpr.py
  test/test_loops.py
Labels: CLA Signed

#640 Better error for passing Tile to hl.tile
  helion/exc.py
  helion/language/loops.py
  test/test_errors.py
Labels: CLA Signed

#639 int4_gemm: remove use_default_config=True
  examples/int4_gemm.py
Labels: CLA Signed

#643 [Easy][Benchmark CI] Exit job on any exception, for easier error catching
  .github/workflows/benchmark.yml
Labels: CLA Signed

#645 Avoid skipping CUDA errors that crashes the CUDA context
  helion/autotuner/logger.py
Labels: CLA Signed

#651 Skip test_autotune_random_seed_from_settings on rocm
  test/test_autotuner.py
Labels: CLA Signed, ciflow/rocm, module: rocm

#600 PT Sphinx Theme Test
  docs/_static/helion_logo.png
  docs/conf.py
  pyproject.toml
Labels: CLA Signed

#649 Print `static_shapes` settings value along with config for accurate repro
  helion/autotuner/base_search.py
  helion/runtime/kernel.py
Labels: CLA Signed

#662 Fix misaligned address error for matmul
  helion/_compiler/indexing_strategy.py
  test/test_tensor_descriptor.expected
  test/test_tensor_descriptor.py
Labels: CLA Signed

#666 skip gather_gemv code check for B200 and fb_code
  test/test_examples.py
Labels: CLA Signed

#664 rms_norm: get weight from function args
  examples/rms_norm.py
Labels: CLA Signed

#494 [example] fused_linear_jsd
  benchmarks/run.py
  examples/fused_linear_jsd.py
  test/test_examples.expected
  test/test_examples.py
Labels: CLA Signed

#674 Fix CI by moving B200 to cuda13 and downgrade a100/h100 to cuda12.8
  .github/matrix.json
  test/test_loops.expected
  test/test_reductions.expected
Labels: CLA Signed

#663 No background image
  docs/_static/helion_nobackground.png
  docs/conf.py
Labels: CLA Signed

#680 [CI] Fix missing setuptools
  .github/workflows/test.yml
Labels: CLA Signed

#624 faster rms norm backwards kernel
  examples/rms_norm.py
  test/test_examples.expected
  test/test_examples.py
Labels: CLA Signed

#682 [Benchmark CI] Use do_bench cudagraph to avoid profiler failure; select specific kernel impls to run
  .github/workflows/benchmark.yml
  benchmarks/run.py
Labels: CLA Signed

#694 [Benchmark CI] use --op instead of --kernel for better tritonbench compat
  .github/workflows/benchmark.yml
Labels: CLA Signed

#691 Increase tolerance for _validate_against_baseline
  helion/autotuner/base_search.py
Labels: CLA Signed

#692 Support HELION_AUTOTUNE_ACCURACY_CHECK=0
  helion/autotuner/base_search.py
  helion/runtime/settings.py
Labels: CLA Signed

#669 rms norm: improve fwd perf
  examples/rms_norm.py
  test/test_examples.expected
Labels: CLA Signed

#684 [Autotune] Skip Triton shared memory OOM
  helion/autotuner/logger.py
Labels: CLA Signed

#699 [Benchmark CI] Customizable num_inputs for each kernel
  .github/workflows/benchmark.yml
  benchmarks/run.py
Labels: CLA Signed

#695 Run autotune with TRITON_LOCAL_BUILD=1
  helion/autotuner/base_search.py
Labels: CLA Signed

#701 [Benchmark CI] fix layer_norm mapping bug
  benchmarks/run.py
Labels: CLA Signed

#700 [Benchmark CI] Allow customized mapping into tritonbench impls
  .github/workflows/benchmark.yml
  benchmarks/run.py
Labels: CLA Signed

#697 Increase test timeout to 60
  .github/workflows/test.yml
Labels: CLA Signed

#706 Revert "[Benchmark CI] Run rms_norm-bwd and layer_norm-bwd kernels"
  benchmarks/run.py
Labels: CLA Signed, ci-no-td

#707 Revert "[Benchmark CI] Add `--list-kernels-for-benchmark-ci` to benchmark runner"
  .github/workflows/benchmark.yml
  benchmarks/run.py
Labels: CLA Signed, ci-no-td

#708 [Benchmark CI] Run `rms_norm-bwd` and `layer_norm-bwd` kernels
  .github/workflows/benchmark.yml
  benchmarks/run.py
Labels: CLA Signed

#709 [Benchmark CI] Run fewer inputs for layer_norm-bwd to avoid job timeout
  benchmarks/run.py
Labels: CLA Signed

#710 [Benchmark CI] Set tolerance values that match autotuner setting
  benchmarks/run.py
Labels: CLA Signed

#712 [Benchmark CI] Skip last input shape for rms_norm-bwd
  benchmarks/run.py
Labels: CLA Signed

#677 Increase default num_generations to 40
  helion/autotuner/differential_evolution.py
Labels: CLA Signed

#696 Add PatternSearch autotuning algorithm
  helion/autotuner/__init__.py
  helion/autotuner/config_fragment.py
  helion/autotuner/pattern_search.py
  helion/runtime/settings.py
  test/test_autotuner.py
Labels: CLA Signed

#720 Upgrade rocm CI to 7.0
  .github/matrix.json
  .github/workflows/benchmark_dispatch.yml
Labels: CLA Signed, ciflow/rocm, module: rocm

#714 Add eviction policy argument to tl.load
  helion/_compiler/indexing_strategy.py
  helion/language/memory_ops.py
  test/test_eviction_policy.expected
  test/test_eviction_policy.py
  test/test_reductions.expected
  test/test_type_propagation.expected
Labels: CLA Signed

#724 [CI] use complete rocm docker images
  .github/matrix.json
  .github/workflows/benchmark_dispatch.yml
Labels: CLA Signed, ciflow/rocm, module: rocm

#704 [Benchmark] jagged_layer_norm kernel and test
  benchmarks/run.py
  examples/jagged_layer_norm.py
  test/test_examples.expected
  test/test_examples.py
Labels: CLA Signed
